### ISSUE TITLE
CUDA out of memory thrown for multi-gpu training

### ISSUE THREAD

**Issue by patriciamdr** [lyuwenyu/RT-DETR#86]
Hi,

whenever I want to train a model on multiple GPUs, a CUDA OOM is thrown after training, during evaluation, specifically when torch.distributed.all_gather_object is called here:

 File "/home/dev/RT-DETR/rtdetr_pytorch/tools/../src/data/coco/coco_eval.py", line 175, in merge
    all_eval_imgs = dist.all_gather(eval_imgs)
 File "/home/dev/RT-DETR/rtdetr_pytorch/tools/../src/misc/dist.py", line 168, in all_gather
    tdist.all_gather_object(data_list, data)
    
The error is also thrown even when the validation batch size is set to 1. Do you have any ideas why this happens and how I can solve this issue? Thanks!

**Comment by lyuwenyu** [comment]
I rerun the code using 8 gpus,  but do not reproduce this problem.  You can try lastest code,   `distributed` using     `tdist.init_process_group(init_method='env://', )` by default.

**Comment by patriciamdr** [comment]
That actually did the trick! Thank you so much :smile:
